### ISSUE TITLE
Running on CoLab has issue

### ISSUE THREAD

**Issue by bsturk** [MauryaRitesh/AI_Lyrics#1]
This is the output:

Diversity: 0.2
Generating with seed: "i will wash away your pain with my tears"
i will wash away your pain with my tearsTraceback (most recent call last):
  File "main.py", line 77, in <module>
    predictions = model.predict(x, verbose=0)[0]
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1441, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_utils.py", line 145, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected lstm_1_input to have shape (40, 40) but got array with shape (40, 236)

**Comment by saran-gangster** [comment]
```python
import numpy as np
X_train = np.reshape(X_train, (X_train.shape[0], 1, X_train.shape[1]))
X_test = np.reshape(X_test, (X_test.shape[0], 1, X_test.shape[1]))
```
you should edit your like this
